openapi: 3.0.0
info:
  title: ChatGPT Plugin API
  description: API for the ChatGPT Plugin with retrieval capabilities.
  version: "1.0.0"
servers:
  - url: https://loplabbet-api-de981bd1f4e4.herokuapp.com
paths:
  /retrieve:
    post:
      summary: Retrieve relevant documents
      description: Retrieves documents relevant to the given query.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The query string to retrieve relevant documents for.
      responses:
        '200':
          description: A list of relevant documents
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    content:
                      type: string
                    score:
                      type: number
        '400':
          description: Bad request

  /.well-known/ai-plugin.json:
    get:
      summary: Get plugin manifest
      description: Returns the plugin manifest file.
      responses:
        '200':
          description: Plugin manifest
          content:
            text/json:
              schema:
                type: string
        '400':
          description: Bad request

  /openapi.yaml:
    get:
      summary: OpenAPI Specification
      description: Returns the OpenAPI specification for this API.
      responses:
        '200':
          description: OpenAPI specification in YAML format
          content:
            text/yaml:
              schema:
                type: string
        '400':
          description: Bad request
